import pytest
import os
import vouch
from vouch.session import TraceSession

def test_strict_mode_rejects_ephemeral():
    # Ensure we don't pick up local keys
    # We can patch os.path.exists to hide keys, or just use a temp dir for cwd?
    # Simpler: patch CryptoManager.load_private_key to fail or ensure paths don't exist

    # We'll rely on the fact that we probably don't have keys in the test env
    # unless generated by other tests.

    # Force "no keys found" by using a fake home/cwd?
    # Or just passing private_key_path=None

    # TraceSession checks:
    # 1. private_key_path arg
    # 2. .vouch/id_rsa
    # 3. ~/.vouch/id_rsa

    # If we ensure none of these exist...

    with pytest.raises(RuntimeError, match="Strict mode enabled: No private key found"):
        # strict=True is default
        TraceSession("test.vch", strict=True, private_key_path=None)

def test_strict_mode_allows_ephemeral_with_flag():
    # Should not raise
    session = TraceSession("test.vch", strict=True, allow_ephemeral=True)
    assert session._ephemeral_key is not None

if __name__ == "__main__":
    pytest.main([__file__])
